# get all ads
GET http://127.0.0.1:8000/api/ads

### -----------------------------------------------------------------

# create ad with no images

POST http://127.0.0.1:8000/api/ads
Content-Type: application/json
Authorization: Token dbdef7e2cd08847828130c4c5948ca3182aab984

{
    "title": "Book for sale",
    "content": "Book",
    "price": "50",
    "category": "IS",
    "item": "Book"
}

### -----------------------------------------------------------------

# create ad with image upload

POST http://127.0.0.1:8000/api/ads
Content-Type: multipart/form-data; boundary=boundary
Authorization: Token dbdef7e2cd08847828130c4c5948ca3182aab984

--boundary
Content-Disposition: form-data; name="title"

Book for sale
--boundary
Content-Disposition: form-data; name="content"

Book
--boundary
Content-Disposition: form-data; name="price"

50
--boundary
Content-Disposition: form-data; name="category"

IS
--boundary
Content-Disposition: form-data; name="item"

Book
--boundary
Content-Disposition: form-data; name="images"; filename="test_img.png"
Content-Type: image/png

< test_img.png
--boundary

### -----------------------------------------------------------------

# create user

POST http://127.0.0.1:8000/api/users
Content-Type: application/json

{
    "username": "John",
    "password": "1234",
    "email": "john@gmail.com"
}

### -----------------------------------------------------------------

# get auth token

POST http://127.0.0.1:8000/api/token
Content-Type: application/json

{
    "username": "John",
    "password": "1234"
}

### -----------------------------------------------------------------

# create message for ad 1

POST http://127.0.0.1:8000/api/messages
Content-Type: application/json
Authorization: Token dbdef7e2cd08847828130c4c5948ca3182aab984

{
    "ad_id": 1,
    "message": "test"
}

### -----------------------------------------------------------------

# list messages for user with token

GET http://127.0.0.1:8000/api/messages/conversations
Content-Type: application/json
Authorization: Token dbdef7e2cd08847828130c4c5948ca3182aab984
